local module = {}

module.STATES_ENUM = {
	MOVEMENT_GAMEMOVEMENT_ENABLED = "MOVEMENT_GAMEMOVEMENT_ENABLED",
	MOVEMENT_DASHING = "MOVEMENT_DASHING",
	MOVEMENT_AIRDASHING = "MOVEMENT_AIRDASHING",
	MOVEMENT_RUNNING = "MOVEMENT_RUNNING",
	MOVEMENT_DRIFTING = "MOVEMENT_DRIFTING",
	MOVEMENT_SLIDING = "MOVEMENT_SLIDING",
	MOVEMENT_FRONT_DASH_COOLDOWN = "MOVEMENT_FRONT_DASH_COOLDOWN",
	MOVEMENT_SIDE_DASH_COOLDOWN = "MOVEMENT_SIDE_DASH_COOLDOWN",
	COMBAT_DOING_COMBAT = "COMBAT_DOING_COMBAT",
	COMBAT_CHARGING_ATTACK = "COMBAT_CHARGING_ATTACK",
	COMBAT_BEING_ATTACKED = "COMBAT_BEING_ATTACKED",
	COMBAT_SKILL_BEING_ATTACKED = 'COMBAT_SKILL_BEING_ATTACKED',
	COMBAT_FULL_STUNNED = "COMBAT_FULL_STUNNED",
	COMBAT_FROZEN_STUNNED = "COMBAT_FROZEN_STUNNED", -- same as the full stunned but you cant roll back with combatknocback module
	COMBAT_SLIGHTLY_STUNNED = "COMBAT_SLIGHTLY_STUNNED",
	COMBAT_CLICKING = "COMBAT_CLICKING",
	COMBAT_BLOCKING = "COMBAT_BLOCKING",
	COMBAT_PARRYING = "COMBAT_PARRYING",
	COMBAT_CROUCHING = "COMBAT_CROUCHING",
	COMBAT_INSKILL = "COMBAT_INSKILL",
	COMBAT_DEFENSE_EFFECT = "COMBAT_DEFENSE_EFFECT",
	COMBAT_IFRAME = "COMBAT_IFRAME",
	COMBAT_COUNTDOWN_STUNNED = "COMBAT_COUNTDOWN_STUNNED",
	COMBAT_IN_COMBO_COOLDOWN = "COMBAT_IN_COMBO_COOLDOWN",
	COMBAT_VARIANT_COOLDOWN = "COMBAT_VARIANT_COOLDOWN",
	COMBAT_AEREO_COOLDOWN = "COMBAT_AEREO_COOLDOWN",
	COMBAT_DISABLED_AUTOROTATE = "COMBAT_DISABLED_AUTOROTATE"
}


return module
